"""
Carbon Intensity Trace Manager
==============================
Manages real or synthetic carbon intensity traces (gCO2eq/kWh).

Supports three data modes:
    1. **Real UK traces** (``carbon_trace_file='real_uk_2023'``):
       Loads genuine hourly carbon intensity data from the UK National
       Grid ESO Carbon Intensity API for the year 2023 (8,760 values).
       Downloaded by ``data/real_traces/fetch_carbon_intensity.py``.
       Data source: https://api.carbonintensity.org.uk/
       Licence: CC BY 4.0, UK National Grid ESO.

    2. **Region-specific synthetic traces** (``carbon_region='germany'``):
       Generated by ``data/electricity_maps.py`` using published lifecycle
       carbon intensity statistics from Ember's Yearly Electricity Data
       (2024 actuals via Our World in Data, CC BY 4.0).
       Includes diurnal cycle, seasonal variation, auto-correlated noise.
       Regions: France (41), Germany (338), India (707), Poland (612),
       Brazil (106 gCO2eq/kWh mean).

    3. **Default synthetic** (no config): Generates a simple sinusoidal
       trace around ci_base with daily/seasonal amplitude for testing.

Operational carbon formula:
    C_op(t) = E_consumed(t) [J] * (1 / 3.6e6) [kWh/J] * CI(t) [gCO2/kWh]

    This follows the GHG Protocol Scope 2 market-based method [2] and
    is consistent with ISO 14064-1 for quantifying GHG emissions [3].

References
----------
[1] UK National Grid ESO. "Carbon Intensity API." 2023.
    https://carbonintensity.org.uk/  (Accessed: 2025-11-15)

[2] GHG Protocol. "Scope 2 Guidance: An amendment to the GHG Protocol
    Corporate Standard." World Resources Institute, 2015.
    https://ghgprotocol.org/scope-2-guidance

[3] ISO 14064-1:2018. "Greenhouse gases -- Part 1: Specification with
    guidance for quantification and reporting of GHG emissions."

[4] Ember. "Yearly Electricity Data, 2024." Available via
    Our World in Data (CC BY 4.0).
    https://ourworldindata.org/grapher/carbon-intensity-electricity
"""

import numpy as np
import os
from typing import Optional


class CarbonTraceManager:
    """
    Manages carbon intensity time series for the simulation.

    The carbon intensity CI(t) is in gCO2eq/kWh and varies over time
    based on the electricity generation mix (renewable vs. fossil).

    For simulation, each round maps to a time step. We can configure
    how many rounds correspond to one hour of real time.
    """

    def __init__(self, config, rng: np.random.Generator = None):
        """
        Initialize carbon trace manager.

        Parameters
        ----------
        config : SimulationConfig
            Simulation configuration.
        rng : np.random.Generator
            Random number generator.
        """
        self.config = config
        self.rng = rng if rng is not None else np.random.default_rng(42)
        self.trace: np.ndarray = np.array([])
        self.rounds_per_hour: int = 10  # 10 rounds = 1 hour of real time
        self.region: str = ""  # region name if using real traces

        if config.carbon_trace_file == 'real_uk_2023':
            self._load_real_uk_trace()
        elif config.carbon_trace_file and os.path.exists(config.carbon_trace_file):
            self._load_real_trace(config.carbon_trace_file)
        elif hasattr(config, 'carbon_region') and config.carbon_region:
            self._load_region_trace(config.carbon_region)
        else:
            self._generate_synthetic_trace()

    def _load_real_uk_trace(self):
        """
        Load real 2023 hourly carbon intensity from UK National Grid API.

        Source: https://carbonintensity.org.uk/
        Downloaded by data/real_traces/fetch_carbon_intensity.py
        """
        from data.real_carbon_traces import RealCarbonTraceLoader
        loader = RealCarbonTraceLoader(rounds_per_hour=self.rounds_per_hour)
        if loader.available:
            self.trace = loader.get_trace(self.config.num_rounds + 1000)
            self.region = 'UK (real, 2023)'
        else:
            # Fallback to synthetic
            self._generate_synthetic_trace()

    def _load_real_trace(self, filepath: str):
        """
        Load real carbon intensity data from CSV file.

        Expected format: one CI value per line (hourly gCO2eq/kWh).
        Supports Electricity Maps export format.
        """
        try:
            import pandas as pd
            df = pd.read_csv(filepath)
            # Try common column names
            for col in ['carbon_intensity', 'ci', 'carbonIntensity',
                        'co2_intensity', 'value']:
                if col in df.columns:
                    self.trace = df[col].values.astype(float)
                    break
            else:
                # Assume single column or first numeric column
                self.trace = df.iloc[:, 0].values.astype(float)
        except Exception:
            # Fallback: try plain text, one value per line
            self.trace = np.loadtxt(filepath)

        # Clip to physical bounds
        self.trace = np.clip(self.trace, self.config.ci_min, self.config.ci_max)

    def _load_region_trace(self, region: str):
        """
        Load carbon intensity trace for a specific region using
        Electricity Maps published statistics.

        Parameters
        ----------
        region : str
            Region key: 'france', 'germany', 'india', 'poland', 'brazil'.
        """
        from data.electricity_maps import ElectricityMapsTraces
        gen = ElectricityMapsTraces(rng=self.rng)
        self.trace = gen.generate_trace(region)
        self.region = region
        # Update CI bounds to match region
        self.trace = np.clip(self.trace, self.config.ci_min, self.config.ci_max)

    def _generate_synthetic_trace(self):
        """
        Generate synthetic carbon intensity trace mimicking real patterns.

        Based on France's electricity grid characteristics:
        - Base: ~200 gCO2/kWh (moderate nuclear + renewable mix)
        - Daily cycle: lower at night (wind), higher during day (gas peakers)
        - Seasonal: higher in winter (heating demand), lower in summer (solar)
        - Random variation from weather, demand fluctuations

        Generates 8760 hourly values (one year).
        """
        hours = 8760  # one full year
        t = np.arange(hours)

        # Daily cycle: peak at ~18:00 (hour 18), trough at ~04:00
        daily = self.config.ci_amplitude_daily * np.sin(
            2 * np.pi * (t % 24 - 6) / 24
        )

        # Seasonal cycle: peak in winter (hour ~1000 = mid-January)
        seasonal = self.config.ci_amplitude_seasonal * np.sin(
            2 * np.pi * (t - 1000) / 8760
        )

        # Random noise (auto-correlated for realism)
        raw_noise = self.rng.normal(0, self.config.ci_noise_std, hours)
        # Apply simple exponential smoothing for auto-correlation
        noise = np.zeros(hours)
        noise[0] = raw_noise[0]
        alpha = 0.3  # smoothing factor
        for i in range(1, hours):
            noise[i] = alpha * raw_noise[i] + (1 - alpha) * noise[i - 1]

        # Combine
        ci = self.config.ci_base + daily + seasonal + noise

        # Clip to physical bounds
        self.trace = np.clip(ci, self.config.ci_min, self.config.ci_max)

    def get_ci(self, round_num: int) -> float:
        """
        Get carbon intensity for a specific simulation round.

        Maps simulation round to hourly trace index using rounds_per_hour.
        Wraps around if simulation exceeds trace length.

        Parameters
        ----------
        round_num : int
            Current simulation round.

        Returns
        -------
        float
            Carbon intensity in gCO2eq/kWh.
        """
        hour_index = (round_num // self.rounds_per_hour) % len(self.trace)
        return float(self.trace[hour_index])

    def get_normalized_ci(self, round_num: int) -> float:
        """
        Get carbon intensity normalized to [0, 1].

        Parameters
        ----------
        round_num : int
            Current simulation round.

        Returns
        -------
        float
            Normalized CI in [0, 1].
        """
        ci = self.get_ci(round_num)
        return (ci - self.config.ci_min) / (self.config.ci_max - self.config.ci_min)

    def compute_operational_carbon(self, energy_joules: float,
                                   round_num: int) -> float:
        """
        Compute operational carbon emissions for a given energy consumption.

        C_op = E (J) * (1 / 3.6e6) (kWh/J) * CI(t) (gCO2eq/kWh)

        Parameters
        ----------
        energy_joules : float
            Energy consumed in Joules.
        round_num : int
            Current round (for CI lookup).

        Returns
        -------
        float
            Carbon emissions in gCO2eq.
        """
        ci = self.get_ci(round_num)
        kwh = energy_joules / 3.6e6
        return kwh * ci

    def get_trace_statistics(self) -> dict:
        """Return summary statistics of the carbon trace."""
        return {
            'mean': float(np.mean(self.trace)),
            'std': float(np.std(self.trace)),
            'min': float(np.min(self.trace)),
            'max': float(np.max(self.trace)),
            'median': float(np.median(self.trace)),
            'cv': float(np.std(self.trace) / np.mean(self.trace)),  # coeff of variation
        }

    # ─── GHG Protocol Scope 2/3 Classification ──────────────────────
    # Ref: GHG Protocol Corporate Standard, Ch. 4-5; Scope 2 Guidance
    #      (WRI, 2015); ISO 14064-1:2018.
    #
    # In WSN context:
    #   Scope 1: Direct emissions from node operation (zero for battery nodes)
    #   Scope 2: Indirect emissions from purchased electricity for gateway/BS
    #            charging and edge computing infrastructure.
    #   Scope 3: All other indirect emissions in the value chain:
    #            (a) Embodied carbon of sensor nodes (manufacturing)
    #            (b) Transport carbon (deployment logistics)
    #            (c) End-of-life disposal and e-waste processing
    #            (d) Cloud computing for data aggregation/storage
    #
    # This classification enables reporting aligned with the GHG Protocol
    # Corporate Value Chain (Scope 3) Standard and the EU Corporate
    # Sustainability Reporting Directive (CSRD, 2024).
    # ─────────────────────────────────────────────────────────────────

    def compute_scope2_carbon(self, energy_joules: float,
                              round_num: int) -> float:
        """
        Compute Scope 2 carbon emissions (location-based method).

        Scope 2 = operational energy × grid carbon intensity.
        This is the SAME as compute_operational_carbon() but explicitly
        labelled for GHG Protocol compliance.

        The location-based method uses the average grid CI for the
        region where the gateway/BS draws power.

        Parameters
        ----------
        energy_joules : float
            Energy consumed in Joules (gateway/BS electricity).
        round_num : int
            Current round (for CI lookup).

        Returns
        -------
        float
            Scope 2 emissions in gCO2eq.
        """
        return self.compute_operational_carbon(energy_joules, round_num)

    def compute_scope2_marginal(self, energy_joules: float,
                                round_num: int) -> float:
        """
        Compute Scope 2 carbon using MARGINAL emission factor.

        The marginal emission factor (MEF) reflects the carbon intensity
        of the NEXT unit of electricity generated (the marginal plant),
        which is typically a gas peaker or coal plant during high-demand
        periods.  MEF > average CI during peak demand, MEF < average CI
        during off-peak (when renewables are curtailed).

        This follows the consequential LCA approach (ISO 14044 Annex A)
        and is recommended by Electricity Maps for decision-making:
        "Use marginal for decisions about WHEN to consume electricity."

        Approximation: MEF ≈ CI × (1 + 0.3 × sin(2π × hour/24 - π/2))
        This gives ~30% higher-than-average at peak (18:00) and ~30%
        lower-than-average at trough (06:00).

        Refs: Siler-Evans et al. (2012), ES&T; Electricity Maps (2024).

        Parameters
        ----------
        energy_joules : float
            Energy consumed in Joules.
        round_num : int
            Current round.

        Returns
        -------
        float
            Scope 2 marginal emissions in gCO2eq.
        """
        ci_avg = self.get_ci(round_num)
        hour = (round_num // self.rounds_per_hour) % 24
        # Diurnal marginal factor: peaks at hour 18, troughs at hour 6
        marginal_factor = 1.0 + 0.3 * np.sin(2 * np.pi * (hour - 6) / 24)
        ci_marginal = ci_avg * marginal_factor
        kwh = energy_joules / 3.6e6
        return kwh * ci_marginal

    def compute_scope3_embodied(self, num_nodes: int,
                                embodied_per_node: float) -> float:
        """
        Compute Scope 3 Category 1 emissions (purchased goods).

        Scope 3 upstream: embodied carbon from manufacturing IoT sensors.
        This is a one-time emission at deployment, amortised over the
        mission lifetime in the LCI metric.

        GHG Protocol Scope 3 Category 1: "Purchased goods and services."

        Parameters
        ----------
        num_nodes : int
            Number of sensor nodes deployed.
        embodied_per_node : float
            Embodied carbon per node in gCO2eq.

        Returns
        -------
        float
            Scope 3 Cat.1 emissions in gCO2eq.
        """
        return num_nodes * embodied_per_node

    def compute_scope3_eol(self, dead_count: int, eol_per_node: float,
                           recycle_rate: float) -> float:
        """
        Compute Scope 3 Category 12 emissions (end-of-life treatment).

        Scope 3 downstream: e-waste processing, recycling, landfill.
        Ref: Forti et al. (2024) Global E-waste Monitor, UNU/UNITAR.

        GHG Protocol Scope 3 Category 12: "End-of-life treatment of
        sold products."

        Parameters
        ----------
        dead_count : int
            Number of nodes that have reached end-of-life.
        eol_per_node : float
            EOL carbon per node in gCO2eq.
        recycle_rate : float
            Material recovery rate (0-1).

        Returns
        -------
        float
            Scope 3 Cat.12 emissions in gCO2eq.
        """
        return dead_count * eol_per_node * (1.0 - recycle_rate)

    def get_ghg_scope_breakdown(self, energy_joules: float, round_num: int,
                                num_nodes: int, dead_count: int,
                                embodied_per_node: float = 10000.0,
                                eol_per_node: float = 500.0,
                                recycle_rate: float = 0.3) -> dict:
        """
        Compute full GHG Protocol Scope 1/2/3 breakdown.

        Returns
        -------
        dict
            {'scope1': 0, 'scope2_location': ..., 'scope2_marginal': ...,
             'scope3_embodied': ..., 'scope3_eol': ..., 'total': ...}
        """
        s2_loc = self.compute_scope2_carbon(energy_joules, round_num)
        s2_mar = self.compute_scope2_marginal(energy_joules, round_num)
        s3_emb = self.compute_scope3_embodied(num_nodes, embodied_per_node)
        s3_eol = self.compute_scope3_eol(dead_count, eol_per_node, recycle_rate)
        return {
            'scope1': 0.0,           # no direct combustion in battery WSN
            'scope2_location': s2_loc,
            'scope2_marginal': s2_mar,
            'scope3_embodied': s3_emb,
            'scope3_eol': s3_eol,
            'total': s2_loc + s3_emb + s3_eol,
        }
